server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://101.37.166.113:27017/test      # ip:端口/数据库
  redis:
    host: elasticsearch #Linux虚拟机上 #没有设置密码
    port: 6379
    database: 10
    timeout: 5000
    password: 123456
    client-type: jedis


